# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    end_eff_controller:
      type: position_controllers/GripperActionController


    arm_planner_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

end_eff_controller:
  ros__parameters:
    joint: j5
arm_planner_controller:
  ros__parameters:
    joints:
      - j1
      - j2
      - j3
      - j4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
